# syntax=docker/dockerfile:1.7

FROM golang:1.26

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && go install github.com/air-verse/air@v1.67.4

EXPOSE 8082 50052

CMD ["air"]
