services:
  service-mock-generator:
    build: .
    environment:
      APP_ENV: development
      CONFIG_PATH: /app/configs/development.yaml
      SERVICE_AUTH_JWKS_URL: http://host.docker.internal:8180/realms/endge-local/protocol/openid-connect/certs
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - "8082"
      - "50052"
