// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mockdata/v1/mockdata.proto

package mockdatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Only authenticated service callers may set trusted owner context.
type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{0}
}

func (x *Owner) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Owner) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{1}
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfo) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// JSON bytes preserve arbitrary JSON roots and exact numeric literals.
type JSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONResponse) Reset() {
	*x = JSONResponse{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONResponse) ProtoMessage() {}

func (x *JSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONResponse.ProtoReflect.Descriptor instead.
func (*JSONResponse) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{3}
}

func (x *JSONResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *Owner                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Json          []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *GenerateRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type CreateStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *Owner                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Json          []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamRequest) Reset() {
	*x = CreateStreamRequest{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamRequest) ProtoMessage() {}

func (x *CreateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamRequest.ProtoReflect.Descriptor instead.
func (*CreateStreamRequest) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{5}
}

func (x *CreateStreamRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *CreateStreamRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type StreamReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *Owner                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReference) Reset() {
	*x = StreamReference{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReference) ProtoMessage() {}

func (x *StreamReference) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReference.ProtoReflect.Descriptor instead.
func (*StreamReference) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{6}
}

func (x *StreamReference) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *StreamReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamReference       `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	PatchJson     []byte                 `protobuf:"bytes,2,opt,name=patch_json,json=patchJson,proto3" json:"patch_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamRequest) Reset() {
	*x = UpdateStreamRequest{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamRequest) ProtoMessage() {}

func (x *UpdateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamRequest.ProtoReflect.Descriptor instead.
func (*UpdateStreamRequest) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStreamRequest) GetStream() *StreamReference {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *UpdateStreamRequest) GetPatchJson() []byte {
	if x != nil {
		return x.PatchJson
	}
	return nil
}

type StreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mockdata_v1_mockdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_mockdata_v1_mockdata_proto_rawDescGZIP(), []int{8}
}

func (x *StreamEvent) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_mockdata_v1_mockdata_proto protoreflect.FileDescriptor

const file_mockdata_v1_mockdata_proto_rawDesc = "" +
	"\n" +
	"\x1amockdata/v1/mockdata.proto\x12\vmockdata.v1\"E\n" +
	"\x05Owner\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\"\a\n" +
	"\x05Empty\"S\n" +
	"\vServiceInfo\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\"\"\n" +
	"\fJSONResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"O\n" +
	"\x0fGenerateRequest\x12(\n" +
	"\x05owner\x18\x01 \x01(\v2\x12.mockdata.v1.OwnerR\x05owner\x12\x12\n" +
	"\x04json\x18\x02 \x01(\fR\x04json\"S\n" +
	"\x13CreateStreamRequest\x12(\n" +
	"\x05owner\x18\x01 \x01(\v2\x12.mockdata.v1.OwnerR\x05owner\x12\x12\n" +
	"\x04json\x18\x02 \x01(\fR\x04json\"K\n" +
	"\x0fStreamReference\x12(\n" +
	"\x05owner\x18\x01 \x01(\v2\x12.mockdata.v1.OwnerR\x05owner\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"j\n" +
	"\x13UpdateStreamRequest\x124\n" +
	"\x06stream\x18\x01 \x01(\v2\x1c.mockdata.v1.StreamReferenceR\x06stream\x12\x1d\n" +
	"\n" +
	"patch_json\x18\x02 \x01(\fR\tpatchJson\"!\n" +
	"\vStreamEvent\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json2\x91\x05\n" +
	"\x0fMockDataService\x12>\n" +
	"\x0eGetServiceInfo\x12\x12.mockdata.v1.Empty\x1a\x18.mockdata.v1.ServiceInfo\x12@\n" +
	"\x0fGetCapabilities\x12\x12.mockdata.v1.Empty\x1a\x19.mockdata.v1.JSONResponse\x12C\n" +
	"\bGenerate\x12\x1c.mockdata.v1.GenerateRequest\x1a\x19.mockdata.v1.JSONResponse\x12K\n" +
	"\fCreateStream\x12 .mockdata.v1.CreateStreamRequest\x1a\x19.mockdata.v1.JSONResponse\x12D\n" +
	"\tGetStream\x12\x1c.mockdata.v1.StreamReference\x1a\x19.mockdata.v1.JSONResponse\x12K\n" +
	"\x0fSubscribeStream\x12\x1c.mockdata.v1.StreamReference\x1a\x18.mockdata.v1.StreamEvent0\x01\x12K\n" +
	"\fUpdateStream\x12 .mockdata.v1.UpdateStreamRequest\x1a\x19.mockdata.v1.JSONResponse\x12J\n" +
	"\x0fKeepAliveStream\x12\x1c.mockdata.v1.StreamReference\x1a\x19.mockdata.v1.JSONResponse\x12>\n" +
	"\n" +
	"StopStream\x12\x1c.mockdata.v1.StreamReference\x1a\x12.mockdata.v1.EmptyBHZFgithub.com/endge-lab/service-mock-generator/api/mockdata/v1;mockdatav1b\x06proto3"

var (
	file_mockdata_v1_mockdata_proto_rawDescOnce sync.Once
	file_mockdata_v1_mockdata_proto_rawDescData []byte
)

func file_mockdata_v1_mockdata_proto_rawDescGZIP() []byte {
	file_mockdata_v1_mockdata_proto_rawDescOnce.Do(func() {
		file_mockdata_v1_mockdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mockdata_v1_mockdata_proto_rawDesc), len(file_mockdata_v1_mockdata_proto_rawDesc)))
	})
	return file_mockdata_v1_mockdata_proto_rawDescData
}

var file_mockdata_v1_mockdata_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mockdata_v1_mockdata_proto_goTypes = []any{
	(*Owner)(nil),               // 0: mockdata.v1.Owner
	(*Empty)(nil),               // 1: mockdata.v1.Empty
	(*ServiceInfo)(nil),         // 2: mockdata.v1.ServiceInfo
	(*JSONResponse)(nil),        // 3: mockdata.v1.JSONResponse
	(*GenerateRequest)(nil),     // 4: mockdata.v1.GenerateRequest
	(*CreateStreamRequest)(nil), // 5: mockdata.v1.CreateStreamRequest
	(*StreamReference)(nil),     // 6: mockdata.v1.StreamReference
	(*UpdateStreamRequest)(nil), // 7: mockdata.v1.UpdateStreamRequest
	(*StreamEvent)(nil),         // 8: mockdata.v1.StreamEvent
}
var file_mockdata_v1_mockdata_proto_depIdxs = []int32{
	0,  // 0: mockdata.v1.GenerateRequest.owner:type_name -> mockdata.v1.Owner
	0,  // 1: mockdata.v1.CreateStreamRequest.owner:type_name -> mockdata.v1.Owner
	0,  // 2: mockdata.v1.StreamReference.owner:type_name -> mockdata.v1.Owner
	6,  // 3: mockdata.v1.UpdateStreamRequest.stream:type_name -> mockdata.v1.StreamReference
	1,  // 4: mockdata.v1.MockDataService.GetServiceInfo:input_type -> mockdata.v1.Empty
	1,  // 5: mockdata.v1.MockDataService.GetCapabilities:input_type -> mockdata.v1.Empty
	4,  // 6: mockdata.v1.MockDataService.Generate:input_type -> mockdata.v1.GenerateRequest
	5,  // 7: mockdata.v1.MockDataService.CreateStream:input_type -> mockdata.v1.CreateStreamRequest
	6,  // 8: mockdata.v1.MockDataService.GetStream:input_type -> mockdata.v1.StreamReference
	6,  // 9: mockdata.v1.MockDataService.SubscribeStream:input_type -> mockdata.v1.StreamReference
	7,  // 10: mockdata.v1.MockDataService.UpdateStream:input_type -> mockdata.v1.UpdateStreamRequest
	6,  // 11: mockdata.v1.MockDataService.KeepAliveStream:input_type -> mockdata.v1.StreamReference
	6,  // 12: mockdata.v1.MockDataService.StopStream:input_type -> mockdata.v1.StreamReference
	2,  // 13: mockdata.v1.MockDataService.GetServiceInfo:output_type -> mockdata.v1.ServiceInfo
	3,  // 14: mockdata.v1.MockDataService.GetCapabilities:output_type -> mockdata.v1.JSONResponse
	3,  // 15: mockdata.v1.MockDataService.Generate:output_type -> mockdata.v1.JSONResponse
	3,  // 16: mockdata.v1.MockDataService.CreateStream:output_type -> mockdata.v1.JSONResponse
	3,  // 17: mockdata.v1.MockDataService.GetStream:output_type -> mockdata.v1.JSONResponse
	8,  // 18: mockdata.v1.MockDataService.SubscribeStream:output_type -> mockdata.v1.StreamEvent
	3,  // 19: mockdata.v1.MockDataService.UpdateStream:output_type -> mockdata.v1.JSONResponse
	3,  // 20: mockdata.v1.MockDataService.KeepAliveStream:output_type -> mockdata.v1.JSONResponse
	1,  // 21: mockdata.v1.MockDataService.StopStream:output_type -> mockdata.v1.Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_mockdata_v1_mockdata_proto_init() }
func file_mockdata_v1_mockdata_proto_init() {
	if File_mockdata_v1_mockdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mockdata_v1_mockdata_proto_rawDesc), len(file_mockdata_v1_mockdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mockdata_v1_mockdata_proto_goTypes,
		DependencyIndexes: file_mockdata_v1_mockdata_proto_depIdxs,
		MessageInfos:      file_mockdata_v1_mockdata_proto_msgTypes,
	}.Build()
	File_mockdata_v1_mockdata_proto = out.File
	file_mockdata_v1_mockdata_proto_goTypes = nil
	file_mockdata_v1_mockdata_proto_depIdxs = nil
}
