// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: mockdata/v1/mockdata.proto

package mockdatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MockDataService_GetServiceInfo_FullMethodName  = "/mockdata.v1.MockDataService/GetServiceInfo"
	MockDataService_GetCapabilities_FullMethodName = "/mockdata.v1.MockDataService/GetCapabilities"
	MockDataService_Generate_FullMethodName        = "/mockdata.v1.MockDataService/Generate"
	MockDataService_CreateStream_FullMethodName    = "/mockdata.v1.MockDataService/CreateStream"
	MockDataService_GetStream_FullMethodName       = "/mockdata.v1.MockDataService/GetStream"
	MockDataService_SubscribeStream_FullMethodName = "/mockdata.v1.MockDataService/SubscribeStream"
	MockDataService_UpdateStream_FullMethodName    = "/mockdata.v1.MockDataService/UpdateStream"
	MockDataService_KeepAliveStream_FullMethodName = "/mockdata.v1.MockDataService/KeepAliveStream"
	MockDataService_StopStream_FullMethodName      = "/mockdata.v1.MockDataService/StopStream"
)

// MockDataServiceClient is the client API for MockDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockDataServiceClient interface {
	GetServiceInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceInfo, error)
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*JSONResponse, error)
	CreateStream(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*JSONResponse, error)
	GetStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (*JSONResponse, error)
	SubscribeStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEvent], error)
	UpdateStream(ctx context.Context, in *UpdateStreamRequest, opts ...grpc.CallOption) (*JSONResponse, error)
	KeepAliveStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (*JSONResponse, error)
	StopStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (*Empty, error)
}

type mockDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockDataServiceClient(cc grpc.ClientConnInterface) MockDataServiceClient {
	return &mockDataServiceClient{cc}
}

func (c *mockDataServiceClient) GetServiceInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceInfo)
	err := c.cc.Invoke(ctx, MockDataService_GetServiceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockDataServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, MockDataService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockDataServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, MockDataService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockDataServiceClient) CreateStream(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, MockDataService_CreateStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockDataServiceClient) GetStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, MockDataService_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockDataServiceClient) SubscribeStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MockDataService_ServiceDesc.Streams[0], MockDataService_SubscribeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamReference, StreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MockDataService_SubscribeStreamClient = grpc.ServerStreamingClient[StreamEvent]

func (c *mockDataServiceClient) UpdateStream(ctx context.Context, in *UpdateStreamRequest, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, MockDataService_UpdateStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockDataServiceClient) KeepAliveStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, MockDataService_KeepAliveStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockDataServiceClient) StopStream(ctx context.Context, in *StreamReference, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MockDataService_StopStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockDataServiceServer is the server API for MockDataService service.
// All implementations must embed UnimplementedMockDataServiceServer
// for forward compatibility.
type MockDataServiceServer interface {
	GetServiceInfo(context.Context, *Empty) (*ServiceInfo, error)
	GetCapabilities(context.Context, *Empty) (*JSONResponse, error)
	Generate(context.Context, *GenerateRequest) (*JSONResponse, error)
	CreateStream(context.Context, *CreateStreamRequest) (*JSONResponse, error)
	GetStream(context.Context, *StreamReference) (*JSONResponse, error)
	SubscribeStream(*StreamReference, grpc.ServerStreamingServer[StreamEvent]) error
	UpdateStream(context.Context, *UpdateStreamRequest) (*JSONResponse, error)
	KeepAliveStream(context.Context, *StreamReference) (*JSONResponse, error)
	StopStream(context.Context, *StreamReference) (*Empty, error)
	mustEmbedUnimplementedMockDataServiceServer()
}

// UnimplementedMockDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMockDataServiceServer struct{}

func (UnimplementedMockDataServiceServer) GetServiceInfo(context.Context, *Empty) (*ServiceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedMockDataServiceServer) GetCapabilities(context.Context, *Empty) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedMockDataServiceServer) Generate(context.Context, *GenerateRequest) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedMockDataServiceServer) CreateStream(context.Context, *CreateStreamRequest) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStream not implemented")
}
func (UnimplementedMockDataServiceServer) GetStream(context.Context, *StreamReference) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedMockDataServiceServer) SubscribeStream(*StreamReference, grpc.ServerStreamingServer[StreamEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeStream not implemented")
}
func (UnimplementedMockDataServiceServer) UpdateStream(context.Context, *UpdateStreamRequest) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStream not implemented")
}
func (UnimplementedMockDataServiceServer) KeepAliveStream(context.Context, *StreamReference) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeepAliveStream not implemented")
}
func (UnimplementedMockDataServiceServer) StopStream(context.Context, *StreamReference) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopStream not implemented")
}
func (UnimplementedMockDataServiceServer) mustEmbedUnimplementedMockDataServiceServer() {}
func (UnimplementedMockDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMockDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockDataServiceServer will
// result in compilation errors.
type UnsafeMockDataServiceServer interface {
	mustEmbedUnimplementedMockDataServiceServer()
}

func RegisterMockDataServiceServer(s grpc.ServiceRegistrar, srv MockDataServiceServer) {
	// If the following call panics, it indicates UnimplementedMockDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MockDataService_ServiceDesc, srv)
}

func _MockDataService_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_GetServiceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).GetServiceInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockDataService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockDataService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockDataService_CreateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).CreateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_CreateStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).CreateStream(ctx, req.(*CreateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockDataService_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).GetStream(ctx, req.(*StreamReference))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockDataService_SubscribeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamReference)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MockDataServiceServer).SubscribeStream(m, &grpc.GenericServerStream[StreamReference, StreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MockDataService_SubscribeStreamServer = grpc.ServerStreamingServer[StreamEvent]

func _MockDataService_UpdateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).UpdateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_UpdateStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).UpdateStream(ctx, req.(*UpdateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockDataService_KeepAliveStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).KeepAliveStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_KeepAliveStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).KeepAliveStream(ctx, req.(*StreamReference))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockDataService_StopStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).StopStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDataService_StopStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).StopStream(ctx, req.(*StreamReference))
	}
	return interceptor(ctx, in, info, handler)
}

// MockDataService_ServiceDesc is the grpc.ServiceDesc for MockDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mockdata.v1.MockDataService",
	HandlerType: (*MockDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInfo",
			Handler:    _MockDataService_GetServiceInfo_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _MockDataService_GetCapabilities_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _MockDataService_Generate_Handler,
		},
		{
			MethodName: "CreateStream",
			Handler:    _MockDataService_CreateStream_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _MockDataService_GetStream_Handler,
		},
		{
			MethodName: "UpdateStream",
			Handler:    _MockDataService_UpdateStream_Handler,
		},
		{
			MethodName: "KeepAliveStream",
			Handler:    _MockDataService_KeepAliveStream_Handler,
		},
		{
			MethodName: "StopStream",
			Handler:    _MockDataService_StopStream_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeStream",
			Handler:       _MockDataService_SubscribeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mockdata/v1/mockdata.proto",
}
